import "./css/normalize.css";
import "./css/skeleton.css";
import "./css/pace.css";

import type { Metadata } from "next";
import Script from "next/script";
import { Raleway } from "next/font/google";

const raleway = Raleway({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata: Metadata = {
  title: "KeeLink",
  description: "Generated by create next app",
  icons: ["images/favicon.ico"],
  authors: [{ name: "Andrea Cioni", url: "https://github.com/andreacioni" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* SEO */}
        <meta
          name="description"
          content="KeeLink is a Keepass2Android plug-in that allows everyone to safely share credentials between the smartphone and every other device."
        />

        {/* Mobile Specific Metas */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* JS Library */}

        <Script
          type="text/javascript"
          src="libs/pace/pace.js"
          data-pace-options='{ "ajax": false }'
        />
        <Script type="text/javascript" src="libs/jsencrypt/jsencrypt.min.js" />
        <Script type="text/javascript" src="libs/qrcode/qrcode.min.js" />
        <Script
          type="text/javascript"
          src="libs/sweetalert/sweetalert.min.js"
        />
        <Script type="text/javascript" src="libs/clipboard/clipboard.min.js" />
      </head>
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
