name: Fly Deploy
on:
  push:
    branches:
      - 'master'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18
        - name: Install & Build
          run: |
            cd webapp
            npm ci
            npm run build && npm run move_to_static_dir
            cd ..
            ls -lah static/
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
